#!/usr/bin/python3
import os
import sys

os.system("ip a | grep inet > '/home/salah/.out'")

content = []
for line in open("/home/salah/.out", "r").readlines():
	content.append(line.strip().split(" "))
os.system("rm '/home/salah/.out'")

ip_address = []
for line in content:
	if line[0] == "inet":
		ip_address.append(line[0:2])

ip_addresses = [ip[1] for ip in ip_address]

try:
	ip_index = int(sys.argv[1])
	the_ip = ip_addresses[ip_index]
	print(the_ip[:the_ip.find("/")])
except IndexError:
	print(" | ".join([ip[:ip.find("/")] for ip in ip_addresses]))
